server.port: 8090
spring:
  application:
    name: post-service

  cloud:

    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

    azure:
      servicebus:
        connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}

    function:
      definition: consumer

    stream:
      bindings:
        notification-events:
          destination: notification-events
          producer:
            use-native-encoding: true
        consumer-in-0:
          destination: user-upsert-events
          group: post-service
          consumer:
            auto-startup: true
            max-attempts: 5
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            back-off-max-interval: 30000
      servicebus:
        bindings:
          consumer-in-0:
            consumer:
              auto-complete: false
          notification-events:
            producer:
              entity-type: topic

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

common:
  system:
    listener:
      enabled: true
  local-user:
    enabled: false
  outbox-event:
    enabled: true
    processor:
      task:
        fixed-rate: 5000

# Actuator Endpoints
management:
  metrics:
    distribution.percentiles-histogram.http.server.requests: true
  observations:
    key-values:
      application: post-service
  tracing:
    sampling.probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# Resilience4J Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 10
    instances:
      media:
        base-config: default
      user:
        base-config: default
  # Resilience4J Timeout Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      media:
        base-config: default
      user:
        base-config: default
  # Resilience4J Retry Properties
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 2s
    instances:
      media:
        base-config: default
      user:
        base-config: default