spring:
  datasource:
    url: jdbc:h2:mem:feed-service
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false