server.port: 8761
spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints.web.exposure.include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  observations.key-values:
    application: discovery-server
  tracing.sampling.probability: 1.0